notifications:
  email:
    on_failure: always
    on_success: change
language: python
cache:
 directories:
  - $HOME/miniconda
  - $HOME/virtualenv
env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
python:
  - "3.5"
before_install:
  - . install_conda_pip.sh
install:
  - sudo apt-get update
  - python setup.py build_ext --inplace
  - python setup.py build_sphinx
  - python setup.py install
before_script:
  - pwd
  - ls delight
  - python -c "from delight.io import *"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python scripts/processFilters.py tests/parametersTest.cfg
  - python scripts/processSEDs.py tests/parametersTest.cfg
  - python scripts/simulateWithSEDs.py tests/parametersTest.cfg
script:
  - coverage run --source delight -m py.test
after_success:
  coveralls
